#!/usr/bin/env python3

import sys
from pathlib import Path

ENCODING = "utf-8"
SEPARATOR_WIDTH = 60
COPYRIGHT_HEADER = """\
--
-- Copyright (c) 2026, Mupen64 maintainers.
--
-- SPDX-License-Identifier: GPL-2.0-or-later
--
"""


def make_header(text: str) -> str:
    dashes = "-" * SEPARATOR_WIDTH
    return f"-- {dashes}\n--   {text}\n-- {dashes}\n"


def amalgamate(in_paths, out_path) -> None:
    chunks: list[str] = []

    chunks.append(COPYRIGHT_HEADER)
    chunks.append(
        make_header("THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT DIRECTLY")
    )

    for path in in_paths:
        if not path.exists():
            print(f"[ERROR] File not found: {path}")
            sys.exit(1)
        if not path.is_file():
            print(f"[ERROR] Path is not a file: {path}")
            sys.exit(1)

        try:
            content = path.read_text(encoding=ENCODING)
        except OSError as e:
            print(f"[ERROR] Could not read '{path}': {e}")
            sys.exit(1)

        chunks.append(make_header(path))
        chunks.append(content.rstrip("\n") + "\n")

    amalgamated = "\n".join(chunks)

    try:
        out_path.write_text(amalgamated, encoding=ENCODING)
        print(f"[OK] Written to '{out_path}' ({len(in_paths)} file(s) merged).")
    except OSError as e:
        print(f"[ERROR] Could not write to '{out_path}': {e}")
        sys.exit(1)


if __name__ == "__main__":
    amalgamate(
        [
            Path("src/BreitbandGraphics/breitbandgraphics.lua"),
            Path("src/BreitbandGraphics/types.lua"),
            Path("src/BreitbandGraphics/core.lua"),
            Path("src/BreitbandGraphics/internal.lua"),
            Path("src/BreitbandGraphics/backends/mupen64_d2d.lua"),
            Path("src/BreitbandGraphics/epilogue.lua"),
        ],
        Path("build/breitbandgraphics-amalgamated.lua"),
    )
    amalgamate(
        [
            Path("src/ugui/ugui.lua"),
            Path("src/ugui/types.lua"),
            Path("src/ugui/core.lua"),
            Path("src/ugui/internal.lua"),
            Path("src/ugui/styler.lua"),
            Path("src/ugui/controls/button.lua"),
            Path("src/ugui/controls/toggle_button.lua"),
            Path("src/ugui/controls/carrousel_button.lua"),
            Path("src/ugui/controls/scrollbar.lua"),
            Path("src/ugui/controls/listbox.lua"),
            Path("src/ugui/controls/combobox.lua"),
            Path("src/ugui/controls/textbox.lua"),
            Path("src/ugui/controls/joystick.lua"),
            Path("src/ugui/controls/trackbar.lua"),
            Path("src/ugui/controls/tabcontrol.lua"),
            Path("src/ugui/controls/numberbox.lua"),
            Path("src/ugui/controls/spinner.lua"),
            Path("src/ugui/ugui-ext.lua"),
            Path("src/ugui/epilogue.lua"),
        ],
        Path("build/ugui-amalgamated.lua"),
    )
