[changelog]
header = """
# Summary

This release does something.
"""
body = """{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}**{{ commit.scope }}** {% endif %}\
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}
"""
trim = true
postprocessors = []

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_preprocessors = []
commit_parsers = [
  # We need to check raw_message because footer is currently broken
  { field = "raw_message", pattern = "(?i)changelog:\\s*skip", skip = true },
  { message = "^feat", group = "✨ Features" },
  { message = "^perf", group = "⚡ Performance" },
  { message = "^security", group = "🛡️ Security" },
  { message = "^fix", group = "🐞 Bugfixes" },
  { message = "^doc", group = "📚 Documentation" },
  { footer = "^changelog:\\s*skip\\s*$", skip = true }
]
filter_commits = true
topo_order = false
sort_commits = "newest"
