--
-- Copyright (c) 2026, Mupen64 maintainers.
--
-- SPDX-License-Identifier: GPL-3.0-or-later
--

---@alias LayoutMode
---|"stack" # The control's children are laid out in a stack.

---@class Control
---@field public uid UID The unique identifier of the control.
---@field public styler_mixin any? An optional styler mixin table which can override specific styler parameters for this control.
---@field public rectangle Rectangle? **DEPRECATED - Use `margin`/`size` instead. Note that `rectangle` overrides `margin`/`size` when both are set.** A rectangle defining the control's position and size. The position is treated as an offset from the parent's position, while the size is treated as a forced value.
---@field public is_enabled boolean? Whether the control is enabled. If nil or true, the control is enabled.
---@field public margin SmartUnit2? The control's offset from its parent. If `nil`, `0` is assumed.
---@field public size SmartUnit2? The control's size. If `nil`, `auto` is assumed.
---@field public padding SmartUnit2? Padding around the control's content. If `nil`, the control default padding is used.
---@field public align SmartAlignment2? The control's alignment within its parent. Note that margins are applied after alignment. If `nil`, `0` is assumed.
---@field public layout LayoutMode? The way the control's children are laid out. If `nil`, `stack` is assumed.
---@field public gap SmartUnit? The gap between child controls when using `stack` layout. If `nil`, `0` is assumed.
---@field public direction number? The direction of the layout in the range `[0, 1]`, where `0` is horizontal and `1` is vertical. If `nil`, `0` is assumed.
---@field public tooltip string? The control's tooltip. If nil, no tooltip will be shown.
---@field public plaintext boolean? Whether the control's text content is drawn as plain text without rich rendering.
---@field public z_index integer? The control's Z-index. If nil, `0` is assumed. This control will be drawn in front of siblings with a lower Z-index. To control the Z-index relative to all controls (including parents), parent the control to the scene root.
---@field public hittestable boolean? Whether this control instance participates in hit-testing. Overrides the registry-level `hittestable` function if specified. Defaults to `true` if neither this nor the registry function is set.
---The base class for all controls.
