name: Call org release notifier

permissions:
  contents: read

on:
  release:
    types: [published]

jobs:
  notify:
    uses: mupen64/.github/.github/workflows/notify-release.yml@main
    secrets: inherit
